import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Card from '../components/card'
import Search from '../components/Search'
import { useState,useEffect } from 'react'
import axios from 'axios'
import DropDown from '../components/DropDown'
export default function Home({resturants}) {
  const [searched,setSearched] = useState("");
  const [type,setType] = useState("");
  const [filteredResturants,setFilteredResturants] = useState(resturants);
  const requestSearch = (searchedVal) => {
    if(searchedVal == ""){
      setFilteredResturants(resturants)
    }
      const filter1 = resturants.filter((obj) => {
        return obj.name.toLowerCase().includes(searchedVal.toLowerCase());
      });
      const filtered = filter1.filter((obj) => {
        return obj.type.toLowerCase().includes(type.toLowerCase());
      });
      setFilteredResturants(filtered);

  };
  useEffect(()=>{
    requestSearch(searched);
},[searched,type])

  return (
    <div className={styles.container}>
      <Head>
        <title>Lebanese Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.titleWrapper}>
          <h1 className={styles.title}>Welcome to&nbsp;</h1>
          <h1 className={styles.titlesub}>Lebanese Marketplace</h1>
        </div>
        <div className={styles.searchSection}>
          <div className={styles.searchWrapper}>
            <Search searched={searched} setSearched={setSearched}/>
          </div>
          <div className={styles.dropDownWrapper}>
            <DropDown setType={setType} type={type}/>
          </div>
        </div>
        <div className={styles.grid}>
          <Card resturants={filteredResturants}/>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
export const getServerSideProps = async () => {
  const res1 = await axios.get(`${process.env.NEXT_PUBLIC_CLIENT_URL}/api/resturants`);
  return {
    props: {
      resturants: res1.data
    },
  };
}